# Generated by Django 5.2.8 on 2025-11-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activitylog_checklistitem_comment_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, help_text='ID de 10 dígitos', max_length=10, null=True, unique=True),
        ),
    ]
