# Generated by Django 5.2.8 on 2025-11-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='due_date',
            field=models.DateField(blank=True, help_text='Fecha límite del proyecto/tablero', null=True),
        ),
    ]
